# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a=np.array([1,2,3,4])
print(a)

# Create a 2-dimensional NumPy array using np.array()
b=np.array([[1,2,3,4],[5,6,7,8]])  
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape=",a.shape,"Dimension=",a.ndim,"Data type=",a.dtype,"Size and Type=",a.itemsize)

Shape= (4,) Dimension= 1 Data type= int32 Size and Type= 4


In [4]:
# Attributes of 2-dimensional array
print("Shape=",b.shape,"Dimension=",b.ndim,"Data type=",b.dtype,"Size and Type=",b.itemsize)

Shape= (2, 4) Dimension= 2 Data type= int32 Size and Type= 4


In [5]:
# Create an array of shape (5, 5) with only ones
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros((3,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=((7,2)))

array([[4, 1],
       [8, 2],
       [6, 7],
       [0, 4],
       [0, 7],
       [5, 6],
       [9, 7]])

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.42467524, 0.22999349, 0.82566461, 0.68040657, 0.49479823],
       [0.64843967, 0.41228373, 0.82754502, 0.62619252, 0.6083854 ],
       [0.78299628, 0.12340644, 0.96473008, 0.75392718, 0.51231923]])

In [9]:
# Create an array of normally distributed random numbers
np.random.randint(99,size=((5,6)))

array([[78, 58,  3, 31, 10, 68],
       [12, 76,  3, 32, 70, 77],
       [22, 32, 70, 36, 95, 97],
       [60, 84, 70, 40, 20, 23],
       [63, 57,  9, 84, 65, 60]])

In [10]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
n=np.random.randint(10,size=((4,6)))
print(n)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [11]:
# Copy the code from the cell above and run it again
m=n
print(n)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [12]:
# Find the 0'th index of the latest array you created
m[0,0]

6

In [13]:
# Get the first 2 rows of latest array you created
m[0,:],m[1,:]

(array([6, 3, 7, 4, 6, 9]), array([2, 6, 7, 4, 3, 7]))

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
m[0,:2],m[1,:2]

(array([6, 3]), array([2, 6]))

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
x=np.random.randint(10,size=(3,5))
print(x)
y=np.ones((3,5))
print(y)

[[8 0 9 2 6]
 [3 8 2 4 2]
 [6 4 8 6 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# Add the two arrays together
z=x+y
print(z)

[[ 9.  1. 10.  3.  7.]
 [ 4.  9.  3.  5.  3.]
 [ 7.  5.  9.  7.  2.]]


In [17]:
# Create another array of ones of shape (5, 3)
i=np.ones((5,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Try add the array of ones and the other most recent array together # You can anticipate an 
x+y

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [19]:
# Do the same operation you just did but this time with a transpose on one array
y.T
print(x+y)

[[ 9.  1. 10.  3.  7.]
 [ 4.  9.  3.  5.  3.]
 [ 7.  5.  9.  7.  2.]]


In [20]:
# Take the latest array to the power of 2 using the python way
import math
pow((x+y),2)

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [21]:
# Do the same thing with numpy way
np.power((x+y),2)

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [22]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean((x+y)),np.min((x+y)),np.max((x+y)),np.std((x+y)),np.var((x+y))

(5.6, 1.0, 10.0, 2.8000000000000003, 7.840000000000002)

In [23]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
arr1=np.random.randint(10,size=((3,3)))
arr2=np.random.randint(10,size=((3,2)))
print(arr1)
print(arr2)

[[3 8 1]
 [9 8 9]
 [4 1 3]]
[[6 7]
 [2 0]
 [3 1]]


In [24]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [25]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
a1=np.random.randint(10,size=((4,3)))
a2=np.random.randint(10,size=((4,3)))
print(a1)
print(a2)

[[7 3 1]
 [5 5 9]
 [3 5 1]
 [9 1 9]]
[[3 7 6]
 [8 7 4]
 [1 4 7]
 [9 8 8]]


In [26]:
# Perform a hadamard product on the two newest arrays you created
np.multiply(a1,a2)

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [27]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(arr1,arr2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [28]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
arr2.T
np.dot(arr1,arr2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [29]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
i=np.random.randint(10,size=((3,3)))
j=np.random.randint(10,size=((3,3)))
print(i)
print(j)

[[0 8 6]
 [8 7 0]
 [7 7 2]]
[[0 7 2]
 [2 0 4]
 [9 6 9]]


In [30]:
# Compare the two arrays with '>', '<=' and '==' 
i>j,i<=j,i==j

(array([[False,  True,  True],
        [ True,  True, False],
        [False,  True, False]]), array([[ True, False, False],
        [False, False,  True],
        [ True, False,  True]]), array([[ True, False, False],
        [False, False, False],
        [False, False, False]]))

In [31]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[1, 3, 8],
       [8, 9, 9],
       [1, 3, 4]])

In [32]:
# Sort the indexes of one of the arrays you just created
f=np.argsort(arr1)
print(f)

[[2 0 1]
 [1 0 2]
 [1 2 0]]


In [33]:
# Find the index with the maximum value in one of the arrays you've created
i,j=np.unravel_index(arr1.argmax(), arr1.shape)
print(arr1[i,j])

9


In [34]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a=np.linspace(1,100,10)
print(a)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [35]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.amax(a)

100.0

In [36]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.amin(a)

1.0